version: '3.9'
services:
  hl7-telescoper-api-server:
    build:
      context: .
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      # allowing you to modify the code without having to rebuild the image.
      - .:/app
      # Just specify a path and let the Engine create a volume.
      # Data present in the base image at the specified mount point will be copied
      # over to the new volume upon volume initialization.
      # node_modules from this new volume will be used and not from your local dev env.
      - /app/node_modules/

    # Set environment variables from this file
    env_file:
      - .env

    # Overwrite any env var defined in .env file (if required)
    environment:
      - NODE_ENV=test
      - MONGO_HOST=mongodb://hl7-telescoper-db/hl7-telescoper
      - DEBUG=hl7-telescoper-api-server:*

    # Link to containers in another service.
    # Links also express dependency between services in the same way as depends_on,
    # so they determine the order of service startup.
    links:
      - hl7-telescoper-db

    command:
      - /bin/sh
      - -c
      - yarn && yarn test
  hl7-telescoper-db:
    image: "mongo:4.2.22"
    ports:
      - "27017:27017"
